version: '2'

services:
  pg:
    image: docker.io/bitnami/postgresql:14
    env_file:
      - database.env
    ports:
      - '5445:5432'
    expose:
      - '5445'
    volumes:
      - 'pg_data:/bitnami/postgresql'
    environment :
      - 'ALLOW_EMPTY_PASSWORD=yes'
    
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3315:3306'
    expose:
      # Opens port 3306 on the container
      - '3315'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    
volumes:
  pg_data: 
    driver: local
  my-db: 
    driver: local
